name: Android CI

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Make files executable
      run: |
        chmod +x ./build.sh
        chmod +x ./gradlew
    - name: Build with Gradle
      run: ./build.sh
